-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siteuserdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siteuserdb` ;

-- -----------------------------------------------------
-- Schema siteuserdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siteuserdb` DEFAULT CHARACTER SET utf8 ;
USE `siteuserdb` ;

-- -----------------------------------------------------
-- Table `siteuser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteuser` ;

CREATE TABLE IF NOT EXISTS `siteuser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `first_name` VARCHAR(20) NULL,
  `last_name` VARCHAR(40) NULL,
  `password` VARCHAR(60) NULL,
  `account_status` VARCHAR(15) NULL DEFAULT 'active',
  `job_title` VARCHAR(45) NULL,
  `salary` INT NULL DEFAULT 0,
  `num_visits` INT NULL DEFAULT 0,
  `user_url` VARCHAR(500) NULL,
  `user_type` VARCHAR(10) NULL DEFAULT 'customer',
  `last_login` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS useruser;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'useruser' IDENTIFIED BY '#3@Us3ruser#3@';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'useruser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `siteuser`
-- -----------------------------------------------------
START TRANSACTION;
USE `siteuserdb`;
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (1, 'LarryKong', 'Larry.Kong@email.com', 'Larry', 'Kong', 'passwd', 'Active', 'Accounting', 89965, 0, 'http://www.robcodes.pro', 'Admin', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (2, 'BuffyHua', 'Buffy.Hua@email.com', 'Buffy', 'Hua', 'passwd', 'Active', 'Accounting', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (3, 'DutchLaFever', 'Dutch.LaFever@email.com', 'Dutch', 'LaFever', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (4, 'MitchelWelch', 'Mitchel.Welch@email.com', 'Mitchel', 'Welch', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (5, 'GingerBijur', 'Ginger.Bijur@email.com', 'Ginger', 'Bijur', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (6, 'AnthonyGoffi', 'Anthony.Goffi@email.com', 'Anthony', 'Goffi', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (7, 'AnthonyKuehn', 'Anthony.Kuehn@email.com', 'Anthony', 'Kuehn', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (8, 'GregReik', 'Greg.Reik@email.com', 'Greg', 'Reik', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (9, 'BrendaChristensen', 'Brenda.Christensen@email.com', 'Brenda', 'Christensen', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (10, 'MikeRamberg', 'Mike.Ramberg@email.com', 'Mike', 'Ramberg', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (11, 'LeroyGibson', 'Leroy.Gibson@email.com', 'Leroy', 'Gibson', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (12, 'Valerie2Goodseat', 'Valerie2.Goodseat@email.com', 'Valerie2', 'Goodseat', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (13, 'MagdaBurrell', 'Magda.Burrell@email.com', 'Magda', 'Burrell', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (14, 'DanStorms', 'Dan.Storms@email.com', 'Dan', 'Storms', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (15, 'MartySuitt', 'Marty.Suitt@email.com', 'Marty', 'Suitt', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (16, 'JamesSpringsteen', 'James.Springsteen@email.com', 'James', 'Springsteen', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (17, 'DaveMarsh', 'Dave.Marsh@email.com', 'Dave', 'Marsh', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (18, 'RichardBower', 'Richard.Bower@email.com', 'Richard', 'Bower', 'passwd', 'Active', 'Software Engineering', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (19, 'Chu ChiKooser', 'Chu Chi.Kooser@email.com', 'Chu Chi', 'Kooser', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (20, 'JeffSutton', 'Jeff.Sutton@email.com', 'Jeff', 'Sutton', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (21, 'BaiHua', 'Bai.Hua@email.com', 'Bai', 'Hua', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (22, 'WilliamTingvold', 'William.Tingvold@email.com', 'William', 'Tingvold', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (23, 'DaveTyler', 'Dave.Tyler@email.com', 'Dave', 'Tyler', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (24, 'TomMutschler', 'Tom.Mutschler@email.com', 'Tom', 'Mutschler', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (25, 'MarcyDivine', 'Marcy.Divine@email.com', 'Marcy', 'Divine', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (26, 'JeffTirpak', 'Jeff.Tirpak@email.com', 'Jeff', 'Tirpak', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (27, 'MichaelShaw', 'Michael.Shaw@email.com', 'Michael', 'Shaw', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (28, 'BarbaraMichelin', 'Barbara.Michelin@email.com', 'Barbara', 'Michelin', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (29, 'ReynaldoCimino', 'Reynaldo.Cimino@email.com', 'Reynaldo', 'Cimino', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (30, 'JoanCoughlan', 'Joan.Coughlan@email.com', 'Joan', 'Coughlan', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (31, 'JodyFanous', 'Jody.Fanous@email.com', 'Jody', 'Fanous', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (32, 'DavidFerguson', 'David.Ferguson@email.com', 'David', 'Ferguson', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (33, 'SarahStriker', 'Sarah.Striker@email.com', 'Sarah', 'Striker', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (34, 'WilliamsSobol', 'Williams.Sobol@email.com', 'Williams', 'Sobol', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (35, 'ChrisRingsdorf', 'Chris.Ringsdorf@email.com', 'Chris', 'Ringsdorf', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (36, 'MarkKordonowy', 'Mark.Kordonowy@email.com', 'Mark', 'Kordonowy', 'passwd', 'Active', 'Database Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (37, 'JackJohnson', 'Jack.Johnson@email.com', 'Jack', 'Johnson', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (38, 'LynnHongslo', 'Lynn.Hongslo@email.com', 'Lynn', 'Hongslo', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (39, 'ChrisChristensen', 'Chris.Christensen@email.com', 'Chris', 'Christensen', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (40, 'JamesChiarelli', 'James.Chiarelli@email.com', 'James', 'Chiarelli', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (41, 'PeterCheatham', 'Peter.Cheatham@email.com', 'Peter', 'Cheatham', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (42, 'LarryHiner', 'Larry.Hiner@email.com', 'Larry', 'Hiner', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (43, 'PatSager', 'Pat.Sager@email.com', 'Pat', 'Sager', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (44, 'DanWerle', 'Dan.Werle@email.com', 'Dan', 'Werle', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (45, 'JudithCoulter', 'Judith.Coulter@email.com', 'Judith', 'Coulter', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (46, 'BobSpearman', 'Bob.Spearman@email.com', 'Bob', 'Spearman', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (47, 'DaveSandlier', 'Dave.Sandlier@email.com', 'Dave', 'Sandlier', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (48, 'DouglasSandberg', 'Douglas.Sandberg@email.com', 'Douglas', 'Sandberg', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (49, 'DougCampbell', 'Doug.Campbell@email.com', 'Doug', 'Campbell', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (50, 'DaveMartindale', 'Dave.Martindale@email.com', 'Dave', 'Martindale', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (51, 'DouglasEngberg', 'Douglas.Engberg@email.com', 'Douglas', 'Engberg', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (52, 'DougSelders', 'Doug.Selders@email.com', 'Doug', 'Selders', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (53, 'HeerTrujillo', 'Heer.Trujillo@email.com', 'Heer', 'Trujillo', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (54, 'Steve O\'Connor', 'Steve .O\'Connor@email.com', 'Steve ', 'O\'Connor', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (55, 'AllanAurand', 'Allan.Aurand@email.com', 'Allan', 'Aurand', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (56, 'RobertNg', 'Robert.Ng@email.com', 'Robert', 'Ng', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (57, 'RebeccaCorrigan', 'Rebecca.Corrigan@email.com', 'Rebecca', 'Corrigan', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (58, 'RickWilms', 'Rick.Wilms@email.com', 'Rick', 'Wilms', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (59, 'HowardSanchez', 'Howard.Sanchez@email.com', 'Howard', 'Sanchez', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (60, 'RickRapoza', 'Rick.Rapoza@email.com', 'Rick', 'Rapoza', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (61, 'JoeDotts', 'Joe.Dotts@email.com', 'Joe', 'Dotts', 'passwd', 'Active', 'System Administrator', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (62, 'CraigBrock', 'Craig.Brock@email.com', 'Craig', 'Brock', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (63, 'KeithSpivey', 'Keith.Spivey@email.com', 'Keith', 'Spivey', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (64, 'JamesSabbe', 'James.Sabbe@email.com', 'James', 'Sabbe', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (65, 'DianeLaFever', 'Diane.LaFever@email.com', 'Diane', 'LaFever', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (66, 'CarolineAnthony', 'Caroline.Anthony@email.com', 'Caroline', 'Anthony', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (67, 'MahnazJones', 'Mahnaz.Jones@email.com', 'Mahnaz', 'Jones', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (68, 'SandraEstrada III', 'Sandra.Estrada III@email.com', 'Sandra', 'Estrada III', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (69, 'RobbiAlmeida', 'Robbi.Almeida@email.com', 'Robbi', 'Almeida', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (70, 'RonalyAlper', 'Ronaly.Alper@email.com', 'Ronaly', 'Alper', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (71, 'LenoraCochran', 'Lenora.Cochran@email.com', 'Lenora', 'Cochran', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (72, 'ConstanceStrawhun', 'Constance.Strawhun@email.com', 'Constance', 'Strawhun', 'passwd', 'Active', 'Chief Executive Officer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (73, 'LauraBrooks', 'Laura.Brooks@email.com', 'Laura', 'Brooks', 'passwd', 'Active', 'Designer', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (74, 'GarnicRogers', 'Garnic.Rogers@email.com', 'Garnic', 'Rogers', 'passwd', 'Active', 'Manager', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (75, 'EleanorHill', 'Eleanor.Hill@email.com', 'Eleanor', 'Hill', 'passwd', 'Active', 'Manager', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (76, 'BarbVaughn', 'Barb.Vaughn@email.com', 'Barb', 'Vaughn', 'passwd', 'Active', 'Manager', 89965, 0, 'http://www.robcodes.pro', 'Customer', '2000-01-01 00:00:00');
INSERT INTO `siteuser` (`id`, `username`, `email`, `first_name`, `last_name`, `password`, `account_status`, `job_title`, `salary`, `num_visits`, `user_url`, `user_type`, `last_login`) VALUES (77, 'adminadmin', 'admin@siteuser.com', 'Admin', 'Admin', 'admin', 'Active', 'System Administrator', 95000, 1, 'http://www.robcodes.pro', 'Admin', '2000-01-01 00:00:00');

COMMIT;

